import Feed from "@/components/Feed";
import Header from "@/components/Header";
import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>Instagram App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/instagram.png" type="image/png" />
      </Head>
      <Header />
      <Feed />
    </div>
  );
}
